server:
    port: 8080

    error:
        include-stacktrace: never
spring:
    application:
        name: vas-payment-api-client

    jackson:
        serialization.write_dates_as_timestamps: false
        default-property-inclusion: non_null

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/postgres
        username: test
        password: test
    jpa:
        open-in-view: true
        show_sql: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false

application:
    vas-payment-server-api:
        base-url: "${VAS_PAYMENT_SERVER_API_URL:https://stage-evc.payex.com/payment-api/api/payments}"
        api-timeout: 20000
        api-key: "${API_KEY:Systemtest}" # Used for HMAC (provided by PayEx)
        api-secret: "${API_SECRET:Systemtest}" # Used for HMAC (provided by PayEx)

    vas-multipay-server-api:
        base-url: "${VAS_MULTIPAY_SERVER_API_URL:https://stage-evc.payex.com/multipay/api/multipay/payment}"
        base-order-url: "${VAS_MULTIPAY_SERVER_ORDER_API_URL:http://localhost:19003/api/orders}"
        api-timeout: 20000
        api-key: "${API_KEY:Systemtest}"
        api-secret: "${API-SECRET:Systemtest}"


vas-payment-api:
    oauth2:
        client:
            grantType: client_credentials
            clientId: "${CLIENT_ID:systemtest}" # Provided by PayEx
            clientSecret: "${CLIENT_SECRET:systemtest}" # Provided by PayEx
            accessTokenUri: "${VAS_AUTH_SERVER_URL:http://noutv002web.utvnet.net/VasIdentityServer/connect/token}"
            scope: publicapi

